include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - avoid_print               # Prohíbe el uso de print() en producción
    - prefer_const_constructors # Exige const en widgets cuando sea posible
    - always_specify_types      # Exige tipos explícitos en funciones, variables y parámetros
    - prefer_final_locals       # Variables locales inmutables cuando sea posible