# Clave única y nombre del proyecto en SonarQube
sonar.organization=piero16301
sonar.projectKey=Piero16301_DataVault_Pro
sonar.projectName=DataVault Pro
sonar.projectVersion=1.0.0

# Rutas del código fuente y pruebas
sonar.sources=lib
sonar.tests=test

# Codificación  
sonar.sourceEncoding=UTF-8

# Cobertura de pruebas para Dart/Flutter
sonar.dart.lcov.reportPaths=coverage/lcov.info

# Exclusiones opcionales
sonar.exclusions=**/*.g.dart, **/*.freezed.dart, lib/generated/**