# Clave única y nombre del proyecto en SonarQube
sonar.projectKey=datavault_pro
sonar.projectName=DataVault Pro
sonar.projectVersion=1.0.0

# Rutas del código fuente y pruebas
sonar.sources=lib
sonar.tests=test

# Codificación  
sonar.sourceEncoding=UTF-8

# URL y Token de SonarQube
sonar.host.url=http://localhost:9000
sonar.login=sqp_6abfcd77d4a5d0c426ae22ea4103e0b982a3a97c

# Exclusiones opcionales para autogenerados
sonar.exclusions=**/*.g.dart, **/*.freezed.dart